// <auto-generated />
using System;
using CompraVenta.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraVenta.Persistence.Migrations
{
    [DbContext(typeof(CompraVentaDbContext))]
    [Migration("20260807043756_AddEntities")]
    partial class AddEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompraVenta.Domain.Entities.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_MovimientoCab");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovementTypeEnum")
                        .HasColumnType("int")
                        .HasColumnName("Id_TipoMovimiento");

                    b.Property<int>("OriginDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("Id_DocumentoOrigen");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FecRegistro");

                    b.HasKey("Id");

                    b.ToTable("MovimientoCab");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.MovementDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_MovimientoDet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovementId")
                        .HasColumnType("int")
                        .HasColumnName("Id_movimientocab");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Producto");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.HasIndex("ProductId");

                    b.ToTable("Movimientodet");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NroLote");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Costo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre_producto");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fec_registro");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("PrecioVenta");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_CompraCab");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FecRegistro");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.ToTable("CompraCab");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_CompraDet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("Id_CompraCab");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Sub_Total");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Precio");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("CompraDet");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_VentaCab");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecRegistro");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.ToTable("Ventacab");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_VentaDet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("Id_VentaCab");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Sub_Total");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Igv");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("Precio");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("VentaDet");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contrasena");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Nombre_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "42ffdc354f77785d52c8bea0fdddb1962f625183da9174c3757e412b06d2932f",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.MovementDetail", b =>
                {
                    b.HasOne("CompraVenta.Domain.Entities.Movement", "Movement")
                        .WithMany("MovementDetails")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraVenta.Domain.Entities.Product", "Product")
                        .WithMany("MovementDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.PurchaseDetail", b =>
                {
                    b.HasOne("CompraVenta.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraVenta.Domain.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.SaleDetail", b =>
                {
                    b.HasOne("CompraVenta.Domain.Entities.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraVenta.Domain.Entities.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Movement", b =>
                {
                    b.Navigation("MovementDetails");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Product", b =>
                {
                    b.Navigation("MovementDetails");

                    b.Navigation("PurchaseDetails");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("CompraVenta.Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
